// <auto-generated />
using System;
using GamingStoreTekrar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamingStoreTekrar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240707123955_mig02")]
    partial class mig02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GameGameTag", b =>
                {
                    b.Property<Guid>("GameTagsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GamesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameTagsId", "GamesId");

                    b.HasIndex("GamesId");

                    b.ToTable("GameGameTag");
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.Property<Guid>("GamesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenresId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GamesId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("GameGenre");
                });

            modelBuilder.Entity("GamingStoreTekrar.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90e838b1-a39a-4f69-a8da-aacbfa11cd11"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(1935),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit minus corrupti voluptate repudiandae assumenda illo consequuntur, quaerat animi. Quisquam, praesentium.",
                            IsDeleted = false,
                            Name = "Call of Duty",
                            PhotoPath = "images/cta-bg.jpg",
                            Price = 60.0,
                            ShortDesc = "Lorem ipsum dolor sit amet consectetur adipisicing elit."
                        },
                        new
                        {
                            Id = new Guid("3b4aeb54-91cc-4fd9-b3a1-9b7f140c4810"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(1954),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas aliquam aspernatur repellendus a, possimus vero at molestias voluptatibus maxime nisi!",
                            IsDeleted = false,
                            Name = "Assassin's Creed",
                            PhotoPath = "images/top-game-01.jpg",
                            Price = 50.0,
                            ShortDesc = "Lorem ipsum dolor sit amet consectetur adipisicing elit."
                        },
                        new
                        {
                            Id = new Guid("3785790e-0c3f-4c6c-90e9-7ff56fb854ca"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(1957),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate quibusdam eveniet voluptatum maiores expedita eos dolore itaque, doloremque ab quae.",
                            IsDeleted = false,
                            Name = "Halo Infinite",
                            PhotoPath = "images/top-game-02.jpg",
                            Price = 70.0,
                            ShortDesc = "Lorem ipsum dolor sit amet consectetur adipisicing elit."
                        },
                        new
                        {
                            Id = new Guid("a5cdaa73-7b0a-40ab-b87c-e530bf623bc5"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(1959),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint aliquid ab esse expedita veritatis eius quia repellendus, ipsam neque odit.",
                            IsDeleted = false,
                            Name = "The Witcher 3: Wild Hunt",
                            PhotoPath = "images/top-game-03.jpg",
                            Price = 40.0,
                            ShortDesc = "Lorem ipsum dolor sit amet consectetur adipisicing elit."
                        },
                        new
                        {
                            Id = new Guid("8caacba0-0990-47db-8402-5dfac9f14327"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(1961),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque, quam exercitationem! Deserunt, obcaecati. Eaque minima tempora velit laudantium.",
                            IsDeleted = false,
                            Name = "Red Dead Redemption 2",
                            PhotoPath = "images/top-game-04.jpg",
                            Price = 55.0,
                            ShortDesc = "Lorem ipsum dolor sit amet consectetur adipisicing elit."
                        },
                        new
                        {
                            Id = new Guid("ad9f426f-532a-4e11-a915-6b5f32830056"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(1966),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur quam deleniti doloribus recusandae sequi, laudantium doloremque quod sit omnis.",
                            IsDeleted = false,
                            Name = "FIFA 22",
                            PhotoPath = "images/top-game-05.jpg",
                            Price = 45.0,
                            ShortDesc = "Lorem ipsum dolor sit amet consectetur adipisicing elit."
                        },
                        new
                        {
                            Id = new Guid("08b5a70f-0f06-4e15-a43e-e3506a3c0a37"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(1968),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem iusto sit quae. Nesciunt, veniam dolorum! Ad, saepe. At, ipsum.",
                            IsDeleted = false,
                            Name = "Minecraft",
                            PhotoPath = "images/top-game-06.jpg",
                            Price = 30.0,
                            ShortDesc = "Lorem ipsum dolor sit amet consectetur adipisicing elit."
                        },
                        new
                        {
                            Id = new Guid("f91f5519-0103-4088-b8f5-1f309d3e88cf"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(1982),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem quis iusto, blanditiis fugit dolorem odit nisi laborum sapiente eius!",
                            IsDeleted = false,
                            Name = "Cyberpunk 2077",
                            PhotoPath = "images/top-game-05.jpg",
                            Price = 50.0,
                            ShortDesc = "Lorem ipsum dolor sit amet consectetur adipisicing elit."
                        },
                        new
                        {
                            Id = new Guid("0d9cbc14-1f33-4792-9278-0a8ad50d1755"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(1984),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Fugiat quaerat molestiae laborum corporis, laudantium odit voluptate eligendi tempore vero!",
                            IsDeleted = false,
                            Name = "The Last of Us Part II",
                            PhotoPath = "images/top-game-03.jpg",
                            Price = 45.0,
                            ShortDesc = "Lorem ipsum dolor sit amet consectetur adipisicing elit."
                        },
                        new
                        {
                            Id = new Guid("ae364d6f-fb3d-4714-a21a-cfb22b2ba05d"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(1987),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Veniam nihil odio quos doloribus maiores, laborum minus, quibusdam distinctio consequatur!",
                            IsDeleted = false,
                            Name = "Grand Theft Auto V",
                            PhotoPath = "images/top-game-02.jpg",
                            Price = 40.0,
                            ShortDesc = "Lorem ipsum dolor sit amet consectetur adipisicing elit."
                        },
                        new
                        {
                            Id = new Guid("b949cd63-b760-4cd0-b8a8-6953f98474ac"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(1990),
                            Description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Adipisci voluptas exercitationem reiciendis iure eius dolorem excepturi molestias dolorum voluptatibus.",
                            IsDeleted = false,
                            Name = "Fortnite",
                            PhotoPath = "images/top-game-04.jpg",
                            Price = 0.0,
                            ShortDesc = "Lorem ipsum dolor sit amet consectetur adipisicing elit."
                        });
                });

            modelBuilder.Entity("GamingStoreTekrar.Entities.GameTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GameTags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f66c6a9c-af2a-426a-89dd-7fabc465b162"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(2117),
                            IsDeleted = false,
                            Name = "War"
                        },
                        new
                        {
                            Id = new Guid("67fedf7c-b775-41ed-a595-7bf345000057"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(2120),
                            IsDeleted = false,
                            Name = "Crafting"
                        },
                        new
                        {
                            Id = new Guid("c2bbbe97-c386-4794-9fe4-71a3681ac920"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(2122),
                            IsDeleted = false,
                            Name = "Survival"
                        });
                });

            modelBuilder.Entity("GamingStoreTekrar.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ec9fb7ce-51c3-4a6a-a1b4-df35476e5469"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(2066),
                            IsDeleted = false,
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("d4c31d11-9e1b-4f9d-8903-1c326d2b5ae0"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(2070),
                            IsDeleted = false,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = new Guid("561acae1-6df0-417e-b077-851e4e323c40"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(2072),
                            IsDeleted = false,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("4f533c75-24ad-4c65-86da-4acee375c169"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(2075),
                            IsDeleted = false,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = new Guid("f95bc565-e706-4443-9552-7b7562368ed2"),
                            CreatedDate = new DateTime(2024, 7, 7, 16, 39, 55, 219, DateTimeKind.Local).AddTicks(2081),
                            IsDeleted = false,
                            Name = "Battle royale"
                        });
                });

            modelBuilder.Entity("GameGameTag", b =>
                {
                    b.HasOne("GamingStoreTekrar.Entities.GameTag", null)
                        .WithMany()
                        .HasForeignKey("GameTagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingStoreTekrar.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameGenre", b =>
                {
                    b.HasOne("GamingStoreTekrar.Entities.Game", null)
                        .WithMany()
                        .HasForeignKey("GamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamingStoreTekrar.Entities.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
